name: Scheduled check infrastructure

# PROCESS
#
# This workflow is run on a scheduled basis to check that the infrastructure stack and the IDE stack are compliant with the cdk_nag rules.
#
# 1. Setup codebase and dependencies
# 2. Run the CDK synth command to generate the CloudFormation template for the infrastructure stack
# 3. Run the CDK synth command to generate the CloudFormation template for the IDE stack

# USAGE
#
# NOTE: meant to use as a scheduled task only (or manually for debugging purposes).

on:
  workflow_dispatch:

  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: read

jobs:
  run_cdk_nag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Setup NodeJS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        run: npm ci
      - name: Synth infrastructure
        run: npm run infra:synth -- --c CI=true
      - name: Synth IDE stack
        run: npm run ide:synth -- --c CI=true